<a href="https://colab.research.google.com/github/SantiData87/SantiData87-CoderHouse_DataEngineer_Biblioteca/blob/main/API_Random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Entregable: Proceso ETL en API Random User Generator

In [ ]:
# Importar librerías
import requests
import json
import pandas as pd
import psycopg2

## Descarga de los datos

In [ ]:
# La API devuelve un usuario por cada consulta, por lo que ejecutamos un ciclo para obtener los usuarios deseados
total_users = 20
counter = 0
data = []

while counter < total_users:
  # Hacemos el request a la API
  response = requests.get('https://randomuser.me/api/')
  # Convertimos la data
  data_json = json.loads(response.text)
  data.append(data_json['results'][0])
  counter += 1

In [ ]:
# Convertimos la data a un DataFrame
df = pd.json_normalize(data, sep='_')
df.head()

,gender,email,phone,cell,nat,name_title,name_first,name_last,location_street_number,location_street_name,...,login_sha256,dob_date,dob_age,registered_date,registered_age,id_name,id_value,picture_large,picture_medium,picture_thumbnail
0,female,sayali.bhat@example.com,9913957089,8294317435,IN,Ms,Sayali,Bhat,5433,College St,...,4953a49e27535b5ea739627f1b122a166aae0b095c8666...,1973-11-08T06:59:42.004Z,50,2009-06-22T21:25:40.817Z,14,UIDAI,178782419509,https://randomuser.me/api/portraits/women/69.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...
1,female,ira.drescher@example.com,0437-3592977,0179-8264768,DE,Mrs,Ira,Drescher,2225,Brunnenstraße,...,e6036a8dcbefe5031640773d79cc8d2ccb03fd4bc1e379...,1974-03-23T19:35:02.485Z,50,2002-12-23T07:48:14.027Z,21,SVNR,65 230374 D 750,https://randomuser.me/api/portraits/women/25.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...
2,female,elli.knutsen@example.com,76675906,92032054,NO,Ms,Elli,Knutsen,4945,Solemskogveien,...,72afc3426df41f1e80e9fe42e8381b621bc77ec4b1c649...,1954-01-21T16:46:37.884Z,70,2002-11-10T14:14:24.662Z,21,FN,21015406442,https://randomuser.me/api/portraits/women/13.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...
3,female,noelia.perez@example.com,968-240-931,682-832-643,ES,Ms,Noelia,Pérez,1054,Calle de La Almudena,...,b5d205b9b38523ba971ffddf6e9001fcd578929462cde3...,1962-08-01T11:54:22.099Z,61,2007-07-22T13:01:15.902Z,16,DNI,54740524-X,https://randomuser.me/api/portraits/women/59.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...
4,male,marinko.novak@example.com,013-4159-307,069-1794-587,RS,Mr,Marinko,Novak,273,Partizanski Sastanak,...,e3bf28885e427a1ebd50259c040e1ecf7928d710505488...,1975-04-18T22:38:47.509Z,49,2017-08-29T03:20:33.441Z,6,SID,350751733,https://randomuser.me/api/portraits/men/52.jpg,https://randomuser.me/api/portraits/med/men/52...,https://randomuser.me/api/portraits/thumb/men/...

In [ ]:
df.columns

Index(['gender', 'email', 'phone', 'cell', 'nat', 'name_title', 'name_first',
       'name_last', 'location_street_number', 'location_street_name',
       'location_city', 'location_state', 'location_country',
       'location_postcode', 'location_coordinates_latitude',
       'location_coordinates_longitude', 'location_timezone_offset',
       'location_timezone_description', 'login_uuid', 'login_username',
       'login_password', 'login_salt', 'login_md5', 'login_sha1',
       'login_sha256', 'dob_date', 'dob_age', 'registered_date',
       'registered_age', 'id_name', 'id_value', 'picture_large',
       'picture_medium', 'picture_thumbnail'],
      dtype='object')

In [ ]:
df.dtypes

gender                            object
email                             object
phone                             object
cell                              object
nat                               object
name_title                        object
name_first                        object
name_last                         object
location_street_number             int64
location_street_name              object
location_city                     object
location_state                    object
location_country                  object
location_postcode                 object
location_coordinates_latitude     object
location_coordinates_longitude    object
location_timezone_offset          object
location_timezone_description     object
login_uuid                        object
login_username                    object
login_password                    object
login_salt                        object
login_md5                         object
login_sha1                        object
login_sha256                      object
dob_date                          object
dob_age                            int64
registered_date                   object
registered_age                     int64
id_name                           object
id_value                          object
picture_large                     object
picture_medium                    object
picture_thumbnail                 object
dtype: object

In [ ]:
df.to_csv('data_entregable_1.csv', index=False)

## Entrega 2 - Flujo para almacenar datos en Redshift

In [ ]:
url="data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com"
data_base="data-engineer-database"
user="jese_salazar_coderhouse"
pwd = '4eMu5U9tjv0J'

try:
    conn = psycopg2.connect(
        host=url,
        dbname=data_base,
        user=user,
        password=pwd,
        port='5439'
    )
    print("Conexion to Redshift completada!")

except Exception as e:
    print("No fue posible conectar a Redshift.")
    print(e)

Unable to connect to Redshift.
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "jese_salazar_coderhouse"
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "jese_salazar_coderhouse"

In [ ]:
# Función para cargar los datos
from psycopg2.extras import execute_values

def cargar_en_redshift(conn, table_name, dataframe):
    dtypes= dataframe.dtypes
    cols= list(dtypes.index )
    tipos= list(dtypes.values)
    type_map = {'int64': 'INT','float64': 'FLOAT','object': 'VARCHAR(50)'}
    sql_dtypes = [type_map[str(dtype)] for dtype in tipos]
    # Definir formato SQL VARIABLE TIPO_DATO
    column_defs = [f"{name} {data_type}" for name, data_type in zip(cols, sql_dtypes)]
    # Combine column definitions into the CREATE TABLE statement
    table_schema = f"""
        CREATE TABLE IF NOT EXISTS {table_name} (
            {', '.join(column_defs)}
        );
        """
    # Crear la tabla
    cur = conn.cursor()
    cur.execute(table_schema)
    # Generar los valores a insertar
    values = [tuple(x) for x in dataframe.to_numpy()]
    # Definir el INSERT
    insert_sql = f"INSERT INTO {table_name} ({', '.join(cols)}) VALUES %s"
    # Execute the transaction to insert the data
    cur.execute("BEGIN")
    execute_values(cur, insert_sql, values)
    cur.execute("COMMIT")
    print('Proceso terminado')

In [ ]:
# Carga de datos en RedShift
cargar_en_redshift(conn=conn, table_name='entregable_1', dataframe=df)

NameError: name 'conn' is not defined

In [ ]:
conn.close()